apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: example-comp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: example-comp
    app.kubernetes.io/part-of: example-app
  name: example-comp
  namespace: integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: example-comp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: example-comp
    spec:
      containers:
      - image: quay.io/redhat-appstudio/hacbs-test:d129fc1c11763c9bc7ae2ec16dfbbd67c680e2b2
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
